import type { Vault, Position, Portfolio, VaultRiskReport } from './types';

export const SEED_VAULTS: Vault[] = [
  {
    id: 'vault_001',
    name: 'Morpho USDC Optimizer',
    address: '0x123abc',
    protocol: 'Morpho',
    chain: 'Ethereum',
    asset: 'USDC',
    strategy_type: 'leveraged_lending',
    apy: 8.4,
    tvl: 21000000,
    risk_score: 3.1,
    allocation_score: 76,
    strategy: 'Looped USDC lending strategy on Morpho',
    dependencies: ['Morpho', 'Aave', 'Chainlink'],
    oracle_type: 'Chainlink',
    upgradeability: 'multisig_upgradeable',
    liquidity_depth: 'medium',
    yield_sources: ['borrow_interest', 'incentives'],
    source: 'defillama',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_002',
    name: 'Yearn USDC',
    address: '0x456def',
    protocol: 'Yearn',
    chain: 'Ethereum',
    asset: 'USDC',
    strategy_type: 'lending',
    apy: 6.4,
    tvl: 85000000,
    risk_score: 2.1,
    allocation_score: 91,
    strategy: 'Multi-protocol USDC lending aggregator',
    dependencies: ['Aave', 'Compound', 'Morpho'],
    oracle_type: 'Chainlink',
    upgradeability: 'timelock_upgradeable',
    liquidity_depth: 'high',
    yield_sources: ['lending_interest'],
    source: 'yearn_registry',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_003',
    name: 'Pendle PT-USDC',
    address: '0x789ghi',
    protocol: 'Pendle',
    chain: 'Arbitrum',
    asset: 'USDC',
    strategy_type: 'yield_tokenization',
    apy: 12.8,
    tvl: 15000000,
    risk_score: 4.2,
    allocation_score: 68,
    strategy: 'Fixed yield via principal token',
    dependencies: ['Pendle', 'Aave'],
    oracle_type: 'Chainlink',
    upgradeability: 'immutable',
    liquidity_depth: 'medium',
    yield_sources: ['fixed_yield', 'trading_fees'],
    source: 'pendle_api',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_004',
    name: 'Aave V3 USDC',
    address: '0xabc123',
    protocol: 'Aave',
    chain: 'Ethereum',
    asset: 'USDC',
    strategy_type: 'lending',
    apy: 5.2,
    tvl: 450000000,
    risk_score: 1.8,
    allocation_score: 88,
    strategy: 'Direct USDC lending on Aave V3',
    dependencies: ['Aave'],
    oracle_type: 'Chainlink',
    upgradeability: 'timelock_upgradeable',
    liquidity_depth: 'high',
    yield_sources: ['lending_interest'],
    source: 'aave_subgraph',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_005',
    name: 'Beefy USDC-USDT LP',
    address: '0xdef456',
    protocol: 'Beefy',
    chain: 'Base',
    asset: 'USDC',
    strategy_type: 'lp',
    apy: 9.6,
    tvl: 8500000,
    risk_score: 3.8,
    allocation_score: 72,
    strategy: 'Automated USDC-USDT LP management',
    dependencies: ['Uniswap', 'Beefy'],
    oracle_type: 'Chainlink',
    upgradeability: 'multisig_upgradeable',
    liquidity_depth: 'medium',
    yield_sources: ['trading_fees', 'incentives'],
    source: 'beefy_api',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_006',
    name: 'Gearbox USDC Leveraged',
    address: '0xghi789',
    protocol: 'Gearbox',
    chain: 'Ethereum',
    asset: 'USDC',
    strategy_type: 'leveraged_lending',
    apy: 15.3,
    tvl: 12000000,
    risk_score: 5.1,
    allocation_score: 58,
    strategy: 'Leveraged USDC lending with 3x multiplier',
    dependencies: ['Gearbox', 'Aave', 'Chainlink'],
    oracle_type: 'Chainlink',
    upgradeability: 'multisig_upgradeable',
    liquidity_depth: 'low',
    yield_sources: ['leveraged_interest', 'incentives'],
    source: 'gearbox_api',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_007',
    name: 'Compound III USDC',
    address: '0xjkl012',
    protocol: 'Compound',
    chain: 'Ethereum',
    asset: 'USDC',
    strategy_type: 'lending',
    apy: 4.8,
    tvl: 320000000,
    risk_score: 2.0,
    allocation_score: 85,
    strategy: 'USDC supply on Compound V3',
    dependencies: ['Compound'],
    oracle_type: 'Chainlink',
    upgradeability: 'timelock_upgradeable',
    liquidity_depth: 'high',
    yield_sources: ['lending_interest'],
    source: 'compound_subgraph',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_008',
    name: 'Notional USDC Fixed',
    address: '0xmno345',
    protocol: 'Notional',
    chain: 'Ethereum',
    asset: 'USDC',
    strategy_type: 'lending',
    apy: 7.2,
    tvl: 28000000,
    risk_score: 3.4,
    allocation_score: 74,
    strategy: 'Fixed-rate USDC lending via fCash',
    dependencies: ['Notional', 'Compound'],
    oracle_type: 'Chainlink',
    upgradeability: 'multisig_upgradeable',
    liquidity_depth: 'medium',
    yield_sources: ['fixed_rate_lending'],
    source: 'notional_api',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_009',
    name: 'Sommelier Real Yield USD',
    address: '0xpqr678',
    protocol: 'Sommelier',
    chain: 'Ethereum',
    asset: 'USDC',
    strategy_type: 'delta_neutral',
    apy: 10.5,
    tvl: 18000000,
    risk_score: 4.5,
    allocation_score: 65,
    strategy: 'Delta-neutral strategy with lending and shorts',
    dependencies: ['Sommelier', 'Aave', 'Uniswap'],
    oracle_type: 'Chainlink',
    upgradeability: 'multisig_upgradeable',
    liquidity_depth: 'medium',
    yield_sources: ['lending_interest', 'funding_rates'],
    source: 'sommelier_api',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'vault_010',
    name: 'Maple USDC',
    address: '0xstu901',
    protocol: 'Maple',
    chain: 'Ethereum',
    asset: 'USDC',
    strategy_type: 'lending',
    apy: 9.8,
    tvl: 45000000,
    risk_score: 4.8,
    allocation_score: 62,
    strategy: 'Institutional credit lending pool',
    dependencies: ['Maple'],
    oracle_type: 'Chainlink',
    upgradeability: 'multisig_upgradeable',
    liquidity_depth: 'low',
    yield_sources: ['credit_interest'],
    source: 'maple_subgraph',
    updated_at: '2026-03-14T10:00:00Z',
  },
];

export const SEED_VAULT_RISKS: Record<string, VaultRiskReport> = {
  '0x123abc': {
    address: '0x123abc',
    risk_score: 3.1,
    band: 'low',
    factors: {
      contract_risk: 4,
      dependency_risk: 3,
      oracle_risk: 2,
      liquidity_risk: 3,
      strategy_complexity: 6,
      tvl_volatility: 2,
    },
    notes: [
      'Upgradeable via multisig',
      'Depends on Chainlink oracle',
      'Medium exit liquidity',
    ],
  },
  '0x456def': {
    address: '0x456def',
    risk_score: 2.1,
    band: 'low',
    factors: {
      contract_risk: 2,
      dependency_risk: 2,
      oracle_risk: 2,
      liquidity_risk: 1,
      strategy_complexity: 3,
      tvl_volatility: 1,
    },
    notes: [
      'Battle-tested protocol with 24h timelock',
      'High liquidity depth',
      'Low strategy complexity',
    ],
  },
  '0x789ghi': {
    address: '0x789ghi',
    risk_score: 4.2,
    band: 'medium',
    factors: {
      contract_risk: 3,
      dependency_risk: 4,
      oracle_risk: 3,
      liquidity_risk: 4,
      strategy_complexity: 7,
      tvl_volatility: 4,
    },
    notes: [
      'Immutable contracts reduce upgrade risk',
      'Higher complexity via PT mechanics',
      'Liquidity dependent on trading volume',
    ],
  },
  '0xabc123': {
    address: '0xabc123',
    risk_score: 1.8,
    band: 'low',
    factors: {
      contract_risk: 2,
      dependency_risk: 1,
      oracle_risk: 2,
      liquidity_risk: 1,
      strategy_complexity: 2,
      tvl_volatility: 1,
    },
    notes: [
      'Battle-tested Aave V3',
      'Highest TVL and liquidity',
      'Simple direct lending strategy',
    ],
  },
  '0xdef456': {
    address: '0xdef456',
    risk_score: 3.8,
    band: 'medium',
    factors: {
      contract_risk: 4,
      dependency_risk: 4,
      oracle_risk: 3,
      liquidity_risk: 4,
      strategy_complexity: 5,
      tvl_volatility: 3,
    },
    notes: [
      'LP strategy exposes to impermanent loss',
      'Depends on Uniswap liquidity',
      'Medium exit capacity',
    ],
  },
  '0xghi789': {
    address: '0xghi789',
    risk_score: 5.1,
    band: 'high',
    factors: {
      contract_risk: 5,
      dependency_risk: 5,
      oracle_risk: 4,
      liquidity_risk: 6,
      strategy_complexity: 8,
      tvl_volatility: 5,
    },
    notes: [
      'Leveraged position increases liquidation risk',
      'Low liquidity depth',
      'High complexity and multiple dependencies',
    ],
  },
  '0xjkl012': {
    address: '0xjkl012',
    risk_score: 2.0,
    band: 'low',
    factors: {
      contract_risk: 2,
      dependency_risk: 1,
      oracle_risk: 2,
      liquidity_risk: 1,
      strategy_complexity: 2,
      tvl_volatility: 1,
    },
    notes: [
      'Compound V3 is battle-tested',
      'High liquidity and TVL',
      'Simple direct supply strategy',
    ],
  },
  '0xmno345': {
    address: '0xmno345',
    risk_score: 3.4,
    band: 'medium',
    factors: {
      contract_risk: 4,
      dependency_risk: 3,
      oracle_risk: 3,
      liquidity_risk: 3,
      strategy_complexity: 5,
      tvl_volatility: 2,
    },
    notes: [
      'Fixed-rate mechanics add complexity',
      'Dependency on fCash market liquidity',
      'Upgradeability via multisig',
    ],
  },
  '0xpqr678': {
    address: '0xpqr678',
    risk_score: 4.5,
    band: 'medium',
    factors: {
      contract_risk: 5,
      dependency_risk: 5,
      oracle_risk: 4,
      liquidity_risk: 4,
      strategy_complexity: 7,
      tvl_volatility: 4,
    },
    notes: [
      'Delta-neutral strategy is complex',
      'Multiple protocol dependencies',
      'Relies on arbitrage opportunities',
    ],
  },
  '0xstu901': {
    address: '0xstu901',
    risk_score: 4.8,
    band: 'medium',
    factors: {
      contract_risk: 5,
      dependency_risk: 3,
      oracle_risk: 3,
      liquidity_risk: 6,
      strategy_complexity: 4,
      tvl_volatility: 5,
    },
    notes: [
      'Credit risk from institutional borrowers',
      'Limited liquidity for early exit',
      'Pool-specific underwriting risk',
    ],
  },
};

export const SEED_PORTFOLIO_POSITIONS: Position[] = [
  {
    id: 'pos_001',
    protocol: 'Morpho',
    chain: 'Ethereum',
    position_type: 'vault',
    asset: 'USDC',
    value: 2100000,
    cost_basis: 2000000,
    pnl: 100000,
    vault_address: '0x123abc',
  },
  {
    id: 'pos_002',
    protocol: 'Yearn',
    chain: 'Ethereum',
    position_type: 'vault',
    asset: 'USDC',
    value: 950000,
    cost_basis: 920000,
    pnl: 30000,
    vault_address: '0x456def',
  },
  {
    id: 'pos_003',
    protocol: 'Aave',
    chain: 'Ethereum',
    position_type: 'lending',
    asset: 'USDC',
    value: 1500000,
    cost_basis: 1480000,
    pnl: 20000,
    vault_address: '0xabc123',
  },
  {
    id: 'pos_004',
    protocol: 'Compound',
    chain: 'Ethereum',
    position_type: 'lending',
    asset: 'USDC',
    value: 800000,
    cost_basis: 785000,
    pnl: 15000,
    vault_address: '0xjkl012',
  },
  {
    id: 'pos_005',
    protocol: 'Pendle',
    chain: 'Arbitrum',
    position_type: 'vault',
    asset: 'USDC',
    value: 650000,
    cost_basis: 625000,
    pnl: 25000,
    vault_address: '0x789ghi',
  },
  {
    id: 'pos_006',
    protocol: 'Beefy',
    chain: 'Base',
    position_type: 'lp',
    asset: 'USDC',
    value: 420000,
    cost_basis: 415000,
    pnl: 5000,
    vault_address: '0xdef456',
  },
  {
    id: 'pos_007',
    protocol: 'Curve',
    chain: 'Ethereum',
    position_type: 'lp',
    asset: 'USDC',
    value: 1200000,
    cost_basis: 1180000,
    pnl: 20000,
    vault_address: null,
  },
  {
    id: 'pos_008',
    protocol: 'Aave',
    chain: 'Arbitrum',
    position_type: 'lending',
    asset: 'ETH',
    value: 800000,
    cost_basis: 750000,
    pnl: 50000,
    vault_address: null,
  },
];

export function buildPortfolio(walletAddress: string): Portfolio {
  const positions = SEED_PORTFOLIO_POSITIONS;
  const totalValue = positions.reduce((sum, p) => sum + p.value, 0);

  const assetMap = new Map<string, number>();
  const protocolMap = new Map<string, number>();
  const chainMap = new Map<string, number>();

  positions.forEach((pos) => {
    assetMap.set(pos.asset, (assetMap.get(pos.asset) || 0) + pos.value);
    protocolMap.set(pos.protocol, (protocolMap.get(pos.protocol) || 0) + pos.value);
    chainMap.set(pos.chain, (chainMap.get(pos.chain) || 0) + pos.value);
  });

  const asset_breakdown = Array.from(assetMap.entries()).map(([asset, value]) => ({
    asset,
    value,
    weight: value / totalValue,
  }));

  const protocol_exposure = Array.from(protocolMap.entries()).map(([protocol, value]) => ({
    protocol,
    value,
    weight: value / totalValue,
  }));

  const chain_exposure = Array.from(chainMap.entries()).map(([chain, value]) => ({
    chain,
    value,
    weight: value / totalValue,
  }));

  return {
    wallet_address: walletAddress,
    total_value: totalValue,
    positions,
    asset_breakdown,
    protocol_exposure,
    chain_exposure,
  };
}
